
name: DrowKid

tagline: soy disque desarrollador y programador, pero nomas le hago a la mamada

Image_URL: https://avatars.githubusercontent.com/u/127297730?v=4

Cover_Image: https://picsum.photos/1080?nocache=

links:

  - Name: Página oficial.
    URL: 'https://lalo.my.to/'
    Icon-Class: fa-solid fa-globe
    Color: '#ffffff'
    Text_Color: '#000000'

  - Name: Instagram
    URL: https://www.instagram.com
    Username: lalo_01dk
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

  - Name: GitHub
    URL: http://github.com
    Username: drowkid-1
    Color: '#6e5494'
    Icon-Class: fab fa-github

  - Name: Apps by DrowKid
    URL: 'mailto:support@drowkid.bswc.net'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

  - Name: Blog 
    URL: https://m.me
    Username: drowkid01
    Color: '#006AFF'
    Icon-Class: fab fa fa-circle

  - Name: Telegram
    URL: http://telegram.me
    Username: drowkid01
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

  - Name: Codepen
    URL: https://codepen.io
    Username: 'drowkid-1'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest


footer: 'Yes'

compress_html:
  clippings: all

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# baseurl: /links

markdown: kramdown
