
name: DrowKid

tagline: soy disque desarrollador y programador, pero nomas le hago a la mamada

Image_URL: https://avatars.githubusercontent.com/u/127297730?v=4

Cover_Image: https://picsum.photos/1080?nocache=

links:

  - Name: Mi sitio web.
    URL: 'https://lalo.my.to/'
    Icon-Class: fa-solid fa-globe
    Color: '#ffffff'
    Text_Color: '#000000'

  - Name: Instagram
    URL: https://www.instagram.com
    Username: lalo_01dk
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

  - Name: GitHub
    URL: http://github.com/
    Username: drowkid-1
    Color: '#6e5494'
    Icon-Class: fab fa-github

  - Name: Apps by DrowKid
    URL: 'https://drowapps.bswc.net'
    Icon-Class: fa-brands fa-react
    Color: '#e17055'
    Text_Color: '#ffffff'

  - Name: Code-Blog
    URL: 'https://codeblog-lalo.vercel.app/'
    Color: '#006AFF'
    Icon-Class: fa-solid fa-code

  - Name: Telegram
    URL: http://telegram.me
    Username: drowkid01
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

  - Name: Codepen
    URL: https://codepen.io
    Username: 'drowkid-1'
    Color: '#FFFF4055'
    Icon-Class: fa-brands fa-codepen

  - Name: UI - Componentes Web
    URL: 'https://drowkid-ui.vercel.app/'
    Color: '#FF55FFEA'
    Icon-Class: fa-solid fa-microchip

  - Name: DrowLinks Gen
    URL: 'https://drowkid.vercel.pub/links'
    Color: '#FFFFFC95'
    Icon-Class: fa-solid fa-code

footer: 'Yes'

compress_html:
  clippings: all

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# baseurl: /links

markdown: kramdown
